### ISSUE TITLE
minor typo in listunspent:  bc1 addresses instead of vtc1

### ISSUE THREAD

**Issue by melvincarvalho** [vertcoin/vertcoin#253]
in console type 

vertcoin-cli help listunspent

> vertcoin-cli listunspent 6 9999999 "[\"bc1q09vm5lfy0j5reeulh4x5752q25uqqvz34hufdl\",\"bc1q02ad21edsxd23d32dfgqqsz4vv4nmtfzuklhy3\"]"

**Expected behavior**

the addresses should be vtc1

**Actual behavior**

the addresses are bc1 

**To reproduce**

vertcoin-cli help listunspent

**System information**

command line or console

**Comment by vertiond** [comment]
Thanks, this will be addressed in upcoming v24.2
