### ISSUE TITLE
Vertcoin Wallet not working on M1 Macbook Pro

### ISSUE THREAD

**Issue by abdullahshafin** [vertcoin/vertcoin#254]
# Describe the issue

I downloaded the following 2 installers for VertCoin wallet:  
1. https://github.com/vertcoin-project/vertcoin-core/releases/download/v23.2/vertcoin-23.2-arm64-apple-darwin.dmg2   
2. https://github.com/vertcoin-project/vertcoin-core/releases/download/v23.2/vertcoin-23.2-x86_64-apple-darwin.dmg  

After download, I install them using the drag & drop into the `Applications` folder on a M1 Macbook Pro. Once installed, I open the `Vertcoin Core` application and I receive the following error:  

```
“Vertcoin Core” can’t be opened because Apple cannot check it for malicious software.  
This software needs to be updated. Contact the developer for more information.  
```

### What behavior did you expect?

I expected to see the application and open my wallet.

### What was the actual behavior (provide screenshots if the issue is GUI-related)? 

I receive an error.

### How reliably can you reproduce the issue, what are the steps to do so? 

M1 Macbook Pro  
macOS Monterey version 12.5.1  

### What version of Vertcoin Core are you using, where did you get it (website, self-compiled, etc)?

1. https://github.com/vertcoin-project/vertcoin-core/releases/download/v23.2/vertcoin-23.2-arm64-apple-darwin.dmg2  
2. https://github.com/vertcoin-project/vertcoin-core/releases/download/v23.2/vertcoin-23.2-x86_64-apple-darwin.dmg

**Comment by vertiond** [comment]
macOS builds are codesigned but not yet notarized so they must be manually excluded in the "Privacy & Security" section by selecting "Open anyway".
